from .allocate_to_subject_view import AllocateToSubjectView
from .confirm_stock_view import ConfirmStockView
from .print_labels_view import PrintLabelsView
from .transfer_stock_view import TransferStockView
