# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 20:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import edc_pharma.models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='infusion_number',
            field=models.IntegerField(blank=True, help_text='Only required if dispense type IV or IM is chosen', null=True),
        ),
        migrations.AddField(
            model_name='historicaldispense',
            name='infusion_number',
            field=models.IntegerField(blank=True, help_text='Only required if dispense type IV or IM is chosen', null=True),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='number_of_tablets',
            field=models.IntegerField(blank=True, help_text='Only required if dispense type TABLET, CAPSULES, SUPPOSITORIES is chosen', null=True),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='prepared_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='times_per_day',
            field=models.IntegerField(blank=True, help_text='Only required if dispense type TABLET, CAPSULES, SUPPOSITORIES, SYRUP is chosen', null=True),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only required if IV or IM is chosen', max_digits=5, null=True, verbose_name='Weight in kg'),
        ),
        migrations.AlterField(
            model_name='historicaldispense',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldispense',
            name='number_of_tablets',
            field=models.IntegerField(blank=True, help_text='Only required if dispense type TABLET, CAPSULES, SUPPOSITORIES is chosen', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldispense',
            name='prepared_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicaldispense',
            name='times_per_day',
            field=models.IntegerField(blank=True, help_text='Only required if dispense type TABLET, CAPSULES, SUPPOSITORIES, SYRUP is chosen', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldispense',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only required if IV or IM is chosen', max_digits=5, null=True, verbose_name='Weight in kg'),
        ),
        migrations.AlterField(
            model_name='historicalmedication',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[edc_pharma.models.validate_dob]),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='initials',
            field=models.CharField(help_text='Format is AA or AAA', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{2,3}$', message='Use CAPS, 2-3 letters')]),
        ),
        migrations.AlterField(
            model_name='historicalprotocol',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[edc_pharma.models.validate_dob]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='initials',
            field=models.CharField(help_text='Format is AA or AAA', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{2,3}$', message='Use CAPS, 2-3 letters')]),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='hostname_created',
            field=models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
    ]
