# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispense',
            old_name='iv_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='historicaldispense',
            old_name='iv_duration',
            new_name='duration',
        ),
    ]
