# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='dispense_type',
            field=models.CharField(choices=[('TABLET', 'TABLET'), ('SYRUP', 'SYRUP'), ('IV', 'IV'), ('IM', 'IM'), ('SOLUTION', 'SOLUTION'), ('CAPSULE', 'CAPSULE'), ('SUPPOSITORY', 'SUPPOSITORY')], default='TABLET', max_length=8),
        ),
    ]
