# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenseschedule',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
