# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0002_auto_20161027_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispense',
            name='syrup_dose',
        ),
        migrations.RemoveField(
            model_name='dispense',
            name='total_dosage_volume',
        ),
        migrations.RemoveField(
            model_name='historicaldispense',
            name='syrup_dose',
        ),
        migrations.RemoveField(
            model_name='historicaldispense',
            name='total_dosage_volume',
        ),
        migrations.AddField(
            model_name='dispense',
            name='dose',
            field=models.CharField(blank=True, help_text='Only required if dispense type SYRUP or SOLUTION is chosen', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicaldispense',
            name='dose',
            field=models.CharField(blank=True, help_text='Only required if dispense type SYRUP or SOLUTION is chosen', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='total_volume',
            field=models.CharField(blank=True, help_text='Only required if dispense type is SYRUP, IM, IV is chosen', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldispense',
            name='total_volume',
            field=models.CharField(blank=True, help_text='Only required if dispense type is SYRUP, IM, IV is chosen', max_length=10, null=True),
        ),
    ]
