# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0002_auto_20161026_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispense',
            name='iv_duration',
        ),
        migrations.AddField(
            model_name='dispense',
            name='duration',
            field=models.CharField(blank=True, help_text='Only required if dispense type IV and IM is chosen', max_length=15, null=True),
        ),
    ]
