# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0002_remove_dispense_iv_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='medication',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='edc_pharma.Medication'),
        ),
    ]
