# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 13:56
from __future__ import unicode_literals

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0002_auto_20171001_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseHistory',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('dispense_datetime', models.DateTimeField()),
                ('dispense_timepoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc_pharma.DispenseTimepoint')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalmedication',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmedication',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='historicalprotocol',
            name='history_user',
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['display_index', 'name']},
        ),
        migrations.RemoveField(
            model_name='medication',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='storage_instructions',
        ),
        migrations.AddField(
            model_name='medication',
            name='display_index',
            field=models.IntegerField(db_index=True, default=0, help_text='Index to control display order if not alphabetical, not required', verbose_name='display index'),
        ),
        migrations.AddField(
            model_name='medication',
            name='field_name',
            field=models.CharField(blank=True, editable=False, help_text='Not required', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='short_name',
            field=models.CharField(db_index=True, default='', help_text='This is the stored value, required', max_length=250, unique=True, verbose_name='Stored value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='version',
            field=models.CharField(default='1.0', editable=False, max_length=35),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(db_index=True, help_text='(suggest 40 characters max.)', max_length=250, unique=True, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='HistoricalMedication',
        ),
        migrations.DeleteModel(
            name='HistoricalProtocol',
        ),
        migrations.DeleteModel(
            name='Protocol',
        ),
        migrations.AddField(
            model_name='dispensehistory',
            name='medications',
            field=models.ManyToManyField(blank=True, to='edc_pharma.Medication', verbose_name='Medications dispensed'),
        ),
    ]
