# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatient',
            name='consent_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='consent_date',
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='consent_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 21, 9, 47, 8, 626422, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 21, 9, 47, 8, 626422, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='prepared_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldispense',
            name='prepared_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
