# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0003_auto_20171003_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensehistory',
            name='dispense_timepoint',
        ),
        migrations.RemoveField(
            model_name='dispensehistory',
            name='medications',
        ),
        migrations.DeleteModel(
            name='DispenseHistory',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
