# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0003_auto_20160912_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='iv_duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispense',
            name='medication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edc_pharma.Medication'),
        ),
    ]
