# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0004_auto_20160912_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispense',
            old_name='number_of_tablets_or_teaspoons',
            new_name='number_of_tablets',
        ),
        migrations.AddField(
            model_name='dispense',
            name='number_of_teaspoons',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='dispense',
            unique_together=set([('patient', 'medication', 'prepared_datetime')]),
        ),
    ]
