# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0005_auto_20171004_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DispenseTimepoint',
            new_name='DispenseAppointment',
        ),
        migrations.RemoveField(
            model_name='dispensehistory',
            name='dispense_timepoint',
        ),
        migrations.RemoveField(
            model_name='dispensehistory',
            name='medications',
        ),
        migrations.DeleteModel(
            name='DispenseHistory',
        ),
    ]
