# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0005_auto_20160913_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='iv_duration',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='number_of_tablets',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='number_of_teaspoons',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='total_dosage_volume',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='total_number_of_tablets',
            field=models.IntegerField(blank=True, default=30),
        ),
    ]
