# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0005_auto_20161027_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='total_number_of_tablets',
            field=models.IntegerField(blank=True, help_text='Only required if dispense type TABLET or SUPPOSITORY  is chosen', null=True),
        ),
    ]
