# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 23:14
from __future__ import unicode_literals

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0008_auto_20171012_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False, editable=False)),
                ('dispense_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight in kg')),
                ('duration', models.CharField(max_length=100)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('dispense_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc_pharma.DispenseAppointment')),
            ],
        ),
        migrations.RemoveField(
            model_name='dispensehistory',
            name='dispense_appointment',
        ),
        migrations.RemoveField(
            model_name='dispensehistory',
            name='medication_definition',
        ),
        migrations.RenameField(
            model_name='medicationdefinition',
            old_name='total',
            new_name='strength',
        ),
        migrations.AddField(
            model_name='medicationdefinition',
            name='single_dose',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='medicationdefinition',
            name='use_body_weight',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.DeleteModel(
            name='DispenseHistory',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edc_pharma.MedicationDefinition'),
        ),
    ]
