# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0009_auto_20160913_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='iv_duration',
            field=models.CharField(blank=True, help_text='Only required if dispense type IV is chosen', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='number_of_tablets',
            field=models.IntegerField(blank=True, help_text='Only required if dispense type TABLET is chosen', null=True),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='number_of_teaspoons',
            field=models.IntegerField(blank=True, help_text='Only required if dispense type SYRUP is chosen', null=True),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='total_dosage_volume',
            field=models.CharField(blank=True, help_text='Only required if dispense type SYRUP or IV is chosen', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='total_number_of_tablets',
            field=models.IntegerField(blank=True, help_text='Only required if dispense type TABLET is chosen', null=True),
        ),
    ]
