# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0013_dispenseappointment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenseappointment',
            name='subject_identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='subject_identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject Identifier'),
        ),
    ]
