# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 12:21
from __future__ import unicode_literals

from django.db import migrations
import edc_base.model_fields.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0015_worklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='clinician_initials',
            field=edc_base.model_fields.custom_fields.InitialsField(default='--', help_text='Type 2-3 letters, all in uppercase and no spaces', max_length=3, verbose_name='Clinician initial'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='initials',
            field=edc_base.model_fields.custom_fields.InitialsField(default='--', help_text='Type 2-3 letters, all in uppercase and no spaces', max_length=3, verbose_name='Subject initial'),
        ),
    ]
