# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharma', '0016_auto_20171022_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='recommanded_result',
            field=models.IntegerField(blank=True, null=True, verbose_name='Recommanded quantity'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='arm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Randomization Arm'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prescription category (Capsule or Vials).'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='Duration for prescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='is_approved',
            field=models.BooleanField(default=False, editable=False, verbose_name='Approved?'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='is_consented',
            field=models.NullBooleanField(default=False, verbose_name='Is the consent completed?'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prescription Description'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='result',
            field=models.IntegerField(blank=True, null=True, verbose_name='Auto calculated required quantity'),
        ),
    ]
