from .constants import TABLET, SYRUP, IV, IM, SOLUTION, CAPSULE, SUPPOSITORY

DISPENSE_TYPES = (
    (TABLET, 'TABLET'),
    (SYRUP, 'SYRUP'),
    (IV, 'IV'),
    (IM, 'IM'),
    (SOLUTION, 'SOLUTION'),
    (CAPSULE, 'CAPSULE'),
    (SUPPOSITORY, 'SUPPOSITORY'),
)
