from edc_constants.choices import GENDER
TABLET = 'TABLET'
SYRUP = 'SYRUP'
IV = 'IV'
IM = 'IM'
SOLUTION = 'SOLUTION'
CAPSULE = 'CAPSULE'
SUPPOSITORY = 'SUPPOSITORY'
DISPENSE_TYPES = (
    (TABLET, 'TABLET'),
    (SYRUP, 'SYRUP'),
    (IV, 'IV'),
    (IM, 'IM'),
    (SOLUTION, 'SOLUTION'),
    (CAPSULE, 'CAPSULE'),
    (SUPPOSITORY, 'SUPPOSITORY'),
)
GENDER
