# Generated by Django 3.2.7 on 2021-11-04 01:15

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import edc_utils.date


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('edc_visit_schedule', '0008_auto_20200513_0023'),
        ('edc_action_item', '0028_auto_20210203_0706'),
        ('edc_pharmacy', '0002_auto_20211011_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('edc_visit_schedule.visitschedule',),
        ),
        migrations.RemoveField(
            model_name='historicalrxrefill',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='historicalrxrefill',
            name='start_date',
        ),
        migrations.AddField(
            model_name='historicalrx',
            name='action_identifier',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalrx',
            name='action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.actionitem'),
        ),
        migrations.AddField(
            model_name='historicalrx',
            name='action_item_reason',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalrx',
            name='parent_action_identifier',
            field=models.CharField(blank=True, help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalrx',
            name='parent_action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.actionitem'),
        ),
        migrations.AddField(
            model_name='historicalrx',
            name='related_action_identifier',
            field=models.CharField(blank=True, help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalrx',
            name='related_action_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_action_item.actionitem'),
        ),
        migrations.AddField(
            model_name='historicalrx',
            name='rx_expiration_date',
            field=models.DateField(blank=True, help_text='Leave blank. Will be filled when end of study report is submitted', null=True, verbose_name='Date RX expires'),
        ),
        migrations.AddField(
            model_name='historicalrxrefill',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrxrefill',
            name='number_of_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalrxrefill',
            name='packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrxrefill',
            name='packed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrxrefill',
            name='received_at_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrxrefill',
            name='received_at_site_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrxrefill',
            name='refill_date',
            field=models.DateField(default=edc_utils.date.get_utcnow_as_date, verbose_name='Refill date'),
        ),
        migrations.AddField(
            model_name='historicalrxrefill',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrxrefill',
            name='shipped_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rx',
            name='action_identifier',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rx',
            name='action_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='edc_action_item.actionitem'),
        ),
        migrations.AddField(
            model_name='rx',
            name='action_item_reason',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='rx',
            name='parent_action_identifier',
            field=models.CharField(blank=True, help_text='action identifier that links to parent reference model instance.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rx',
            name='parent_action_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='edc_action_item.actionitem'),
        ),
        migrations.AddField(
            model_name='rx',
            name='related_action_identifier',
            field=models.CharField(blank=True, help_text='action identifier that links to related reference model instance.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rx',
            name='related_action_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='edc_action_item.actionitem'),
        ),
        migrations.AddField(
            model_name='rx',
            name='rx_expiration_date',
            field=models.DateField(blank=True, help_text='Leave blank. Will be filled when end of study report is submitted', null=True, verbose_name='Date RX expires'),
        ),
        migrations.AddField(
            model_name='rxrefill',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rxrefill',
            name='number_of_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rxrefill',
            name='packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rxrefill',
            name='packed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rxrefill',
            name='received_at_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rxrefill',
            name='received_at_site_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rxrefill',
            name='refill_date',
            field=models.DateField(default=edc_utils.date.get_utcnow_as_date, verbose_name='Refill date'),
        ),
        migrations.AddField(
            model_name='rxrefill',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rxrefill',
            name='shipped_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rxrefill',
            unique_together={('rx', 'dosage_guideline', 'refill_date')},
        ),
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('created', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', django_audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', django_audit_fields.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('packed', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('dosage_guideline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edc_pharmacy.dosageguideline')),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edc_pharmacy.formulation')),
                ('rx', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edc_pharmacy.rx')),
                ('site', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import'),
            },
        ),
        migrations.RemoveField(
            model_name='rxrefill',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rxrefill',
            name='start_date',
        ),
    ]
