# Generated by Django 3.2.7 on 2021-10-07 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0007_alter_appointment_appt_reason"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
