# Generated by Django 3.2.7 on 2021-10-07 12:16

import django.db.models.deletion
import edc_registration.models.managers
import edc_sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_registration", "0022_auto_20210801_2021"),
        ("edc_pharmacy", "0010_auto_20211007_1457"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "proxy": True,
                "default_permissions": ("view", "export"),
                "indexes": [],
                "constraints": [],
            },
            bases=("edc_registration.registeredsubject",),
            managers=[
                ("on_site", edc_sites.models.CurrentSiteManager()),
                (
                    "objects",
                    edc_registration.models.managers.RegisteredSubjectManager(),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="registered_subject",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.subject",
                verbose_name="Subject Identifier",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="registered_subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.subject",
                verbose_name="Subject Identifier",
            ),
        ),
    ]
