# Generated by Django 3.2.7 on 2021-10-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0011_auto_20211007_1516"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprescription",
            name="rando_arm",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="rando_arm",
        ),
        migrations.AddField(
            model_name="historicalprescription",
            name="randomizer_name",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="randomizer_name",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
