# Generated by Django 3.2.7 on 2021-10-08 02:55

import _socket
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import edc_pharmacy.models.dispensing_history
import edc_utils.date
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edc_pharmacy', '0012_auto_20211007_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensingHistory',
            fields=[
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('created', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', django_audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', django_audit_fields.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('subject_identifier', models.CharField(max_length=50)),
                ('dispensed_datetime', models.DateTimeField(default=edc_utils.date.get_utcnow)),
                ('dispensed', models.DecimalField(decimal_places=1, max_digits=6)),
                ('status', models.CharField(choices=[('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='dispensed', max_length=25, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Dispensed item',
                'verbose_name_plural': 'Dispensed items',
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import'),
            },
            managers=[
                ('objects', edc_pharmacy.models.dispensing_history.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDispensingHistory',
            fields=[
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('created', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', django_audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', django_audit_fields.fields.uuid_auto_field.UUIDAutoField(blank=True, db_index=True, editable=False, help_text='System auto field. UUID primary key.')),
                ('subject_identifier', models.CharField(max_length=50)),
                ('dispensed_datetime', models.DateTimeField(default=edc_utils.date.get_utcnow)),
                ('dispensed', models.DecimalField(decimal_places=1, max_digits=6)),
                ('status', models.CharField(choices=[('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='dispensed', max_length=25, verbose_name='Status')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dispensed item',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicaldispenseditem',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldispenseditem',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='historicaldispenseditem',
            name='prescription_item',
        ),
        migrations.AlterField(
            model_name='historicalprescription',
            name='rando_sid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprescription',
            name='randomizer_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprescription',
            name='weight_in_kgs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rando_sid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='randomizer_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='weight_in_kgs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='DispensedItem',
        ),
        migrations.DeleteModel(
            name='HistoricalDispensedItem',
        ),
        migrations.AddField(
            model_name='historicaldispensinghistory',
            name='prescription',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_pharmacy.prescription'),
        ),
        migrations.AddField(
            model_name='historicaldispensinghistory',
            name='prescription_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edc_pharmacy.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='dispensinghistory',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edc_pharmacy.prescription'),
        ),
        migrations.AddField(
            model_name='dispensinghistory',
            name='prescription_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edc_pharmacy.prescriptionitem'),
        ),
        migrations.AlterUniqueTogether(
            name='dispensinghistory',
            unique_together={('prescription', 'prescription_item', 'dispensed_datetime')},
        ),
    ]
