# Generated by Django 3.2.7 on 2021-10-08 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharmacy', '0013_auto_20211008_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispensinghistory',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import'), 'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'verbose_name': 'Dispensing history', 'verbose_name_plural': 'Dispensing history'},
        ),
        migrations.AlterModelOptions(
            name='historicaldispensinghistory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Dispensing history'},
        ),
        migrations.RemoveField(
            model_name='historicaldispensinghistory',
            name='prescription',
        ),
        migrations.AlterUniqueTogether(
            name='dispensinghistory',
            unique_together={('prescription_item', 'dispensed_datetime')},
        ),
        migrations.RemoveField(
            model_name='dispensinghistory',
            name='prescription',
        ),
    ]
