# Generated by Django 3.2.7 on 2021-10-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharmacy', '0015_historicalreturnhistory_returnhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensinghistory',
            name='subject_identifier',
        ),
        migrations.RemoveField(
            model_name='historicaldispensinghistory',
            name='subject_identifier',
        ),
        migrations.RemoveField(
            model_name='historicalreturnhistory',
            name='subject_identifier',
        ),
        migrations.RemoveField(
            model_name='returnhistory',
            name='subject_identifier',
        ),
    ]
