# Generated by Django 5.1.2 on 2024-11-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0024_assignment_containerunits_historicalassignment_and_much_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalrequest",
            name="name",
        ),
        migrations.RemoveField(
            model_name="request",
            name="name",
        ),
    ]
