# Generated by Django 5.1.2 on 2024-10-31 16:55

import edc_utils.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_pharmacy",
            "0024_assignment_containerunits_historicalassignment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreceiveitem",
            name="receive_item_datetime",
            field=models.DateTimeField(default=edc_utils.date.get_utcnow),
        ),
        migrations.AddField(
            model_name="receiveitem",
            name="receive_item_datetime",
            field=models.DateTimeField(default=edc_utils.date.get_utcnow),
        ),
    ]
