# Generated by Django 5.1.2 on 2024-11-06 21:57

import _socket
import django.core.validators
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import edc_utils.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0024_assignment_containerunits_historicalassignment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="dosageguideline",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Dosage Guideline",
                "verbose_name_plural": "Dosage Guidelines",
            },
        ),
        migrations.AlterModelOptions(
            name="formulation",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Formulation",
                "verbose_name_plural": "Formulations",
            },
        ),
        migrations.AlterModelOptions(
            name="formulationtype",
            options={
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Formulation type",
                "verbose_name_plural": "Formulation types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalassignment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Assignment",
                "verbose_name_plural": "historical Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldosageguideline",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Dosage Guideline",
                "verbose_name_plural": "historical Dosage Guidelines",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalformulation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Formulation",
                "verbose_name_plural": "historical Formulations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallot",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Lot",
                "verbose_name_plural": "historical Lots",
            },
        ),
        migrations.AlterModelOptions(
            name="lot",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Lot",
                "verbose_name_plural": "Lots",
            },
        ),
        migrations.RemoveField(
            model_name="historicalrepackrequest",
            name="product",
        ),
        migrations.RemoveField(
            model_name="historicalrepackrequest",
            name="stock_identifier",
        ),
        migrations.RemoveField(
            model_name="historicalstock",
            name="repackaging_request",
        ),
        migrations.RemoveField(
            model_name="repackrequest",
            name="product",
        ),
        migrations.RemoveField(
            model_name="repackrequest",
            name="stock_identifier",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="repackaging_request",
        ),
        migrations.AddField(
            model_name="historicalrepackrequest",
            name="confirmed_stock_identifiers",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalrepackrequest",
            name="from_stock",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AddField(
            model_name="historicalrepackrequest",
            name="stock_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalrepackrequest",
            name="stock_identifiers",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalrepackrequest",
            name="unconfirmed_stock_identifiers",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="allocated_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="confirmed_by",
            field=models.CharField(
                blank=True, help_text="label_lower", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="confirmed_by_identifier",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="confirmed_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="subject_identifier",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="repackrequest",
            name="confirmed_stock_identifiers",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repackrequest",
            name="from_stock",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repack_requests",
                to="edc_pharmacy.stock",
            ),
        ),
        migrations.AddField(
            model_name="repackrequest",
            name="stock_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repackrequest",
            name="stock_identifiers",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repackrequest",
            name="stock_items",
            field=models.ManyToManyField(to="edc_pharmacy.stock"),
        ),
        migrations.AddField(
            model_name="repackrequest",
            name="unconfirmed_stock_identifiers",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="allocated_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stock",
            name="confirmed_by",
            field=models.CharField(
                blank=True, help_text="label_lower", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="confirmed_by_identifier",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="confirmed_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="subject_identifier",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="StockUpdate",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "update_identifier",
                    models.CharField(blank=True, max_length=36, null=True, unique=True),
                ),
                ("report_datetime", models.DateTimeField(default=edc_utils.date.get_utcnow)),
                (
                    "source_model",
                    models.CharField(
                        choices=[
                            ("edc_pharmacy.receiveitem", "Receiving"),
                            ("edc_pharmacy.repackrequest", "Repacking"),
                        ],
                        max_length=100,
                        verbose_name="Task",
                    ),
                ),
                (
                    "item_count",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "identifiers",
                    models.TextField(
                        help_text="One per line, no more than 20 per document",
                        verbose_name="Scan labels here",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock update",
                "verbose_name_plural": "Stock updates",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["modified", "created"], name="edc_pharmac_modifie_a77e05_idx"
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="edc_pharmac_user_mo_a81841_idx",
                    ),
                ],
            },
        ),
    ]
