# Generated by Django 5.1.2 on 2024-11-04 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0025_remove_historicalrequest_name_remove_request_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalrequest",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Request",
                "verbose_name_plural": "historical Request",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrequestitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Request item",
                "verbose_name_plural": "historical Request items",
            },
        ),
        migrations.AlterModelOptions(
            name="request",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Request",
                "verbose_name_plural": "Request",
            },
        ),
        migrations.AlterModelOptions(
            name="requestitem",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Request item",
                "verbose_name_plural": "Request items",
            },
        ),
        migrations.AddField(
            model_name="historicalrequestitem",
            name="rx",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.rx",
            ),
        ),
        migrations.AddField(
            model_name="requestitem",
            name="rx",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="edc_pharmacy.rx"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequest",
            name="item_count",
            field=models.IntegerField(
                default=0,
                help_text="Matches the number of Request items.",
                verbose_name="Item count",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrequestitem",
            name="request",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.request",
                verbose_name="Request",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="item_count",
            field=models.IntegerField(
                default=0,
                help_text="Matches the number of Request items.",
                verbose_name="Item count",
            ),
        ),
        migrations.AlterField(
            model_name="requestitem",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.request",
                verbose_name="Request",
            ),
        ),
    ]
