# Generated by Django 5.1.2 on 2024-10-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0025_historicalreceiveitem_receive_item_datetime_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="container",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Stock: Container",
                "verbose_name_plural": "Stock: Containers",
            },
        ),
        migrations.AlterModelOptions(
            name="containertype",
            options={
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Stock: Container type",
                "verbose_name_plural": "Stock: Container types",
            },
        ),
        migrations.AlterModelOptions(
            name="containerunits",
            options={
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Stock: Container units",
                "verbose_name_plural": "Stock: Container units",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstock",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Stock",
                "verbose_name_plural": "historical Stock",
            },
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={
                "default_manager_name": "objects",
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Stock",
                "verbose_name_plural": "Stock",
            },
        ),
    ]
