# Generated by Django 5.1.2 on 2024-11-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0025_alter_assignment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="may_repackage_as",
        ),
        migrations.AddField(
            model_name="container",
            name="may_repack_as",
            field=models.BooleanField(
                default=False, verbose_name="Container may be used for repack request"
            ),
        ),
    ]
