# Generated by Django 5.1.2 on 2024-10-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0026_alter_container_options_alter_containertype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
