# Generated by Django 5.1.2 on 2024-11-07 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0027_remove_historicalstock_receive_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receive",
            name="stock_items",
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="receive_item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.receiveitem",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="receive_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.receiveitem",
            ),
        ),
    ]
