# Generated by Django 5.1.2 on 2024-10-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0027_alter_historicalproduct_name_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallocation",
            name="history_user",
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.AlterModelManagers(
            name="location",
            managers=[],
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="edc_pharmac_modifie_c4a1aa_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="edc_pharmac_user_mo_1838af_idx",
        ),
        migrations.RemoveField(
            model_name="location",
            name="created",
        ),
        migrations.RemoveField(
            model_name="location",
            name="description",
        ),
        migrations.RemoveField(
            model_name="location",
            name="device_created",
        ),
        migrations.RemoveField(
            model_name="location",
            name="device_modified",
        ),
        migrations.RemoveField(
            model_name="location",
            name="hostname_created",
        ),
        migrations.RemoveField(
            model_name="location",
            name="hostname_modified",
        ),
        migrations.RemoveField(
            model_name="location",
            name="locale_created",
        ),
        migrations.RemoveField(
            model_name="location",
            name="locale_modified",
        ),
        migrations.RemoveField(
            model_name="location",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="location",
            name="revision",
        ),
        migrations.RemoveField(
            model_name="location",
            name="user_created",
        ),
        migrations.RemoveField(
            model_name="location",
            name="user_modified",
        ),
        migrations.AddField(
            model_name="location",
            name="display_index",
            field=models.IntegerField(
                default=0,
                help_text="Index to control display order if not alphabetical, not required",
                verbose_name="display index",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="extra_value",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="field_name",
            field=models.CharField(
                blank=True, editable=False, help_text="Not required", max_length=25, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="plural_name",
            field=models.CharField(max_length=250, null=True, verbose_name="Plural name"),
        ),
        migrations.AddField(
            model_name="location",
            name="version",
            field=models.CharField(default="1.0", editable=False, max_length=35),
        ),
        migrations.AlterField(
            model_name="container",
            name="name",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Leave blank to use default",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="display_name",
            field=models.CharField(
                help_text="(suggest 40 characters max.)",
                max_length=250,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                blank=True, help_text="Leave blank to use default", max_length=50, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["display_index", "display_name"], name="edc_pharmac_display_c5b56a_idx"
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalLocation",
        ),
    ]
