# Generated by Django 5.1.2 on 2024-11-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0028_remove_receive_stock_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrepackrequest",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repackrequest",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
