# Generated by Django 5.1.2 on 2024-11-09 21:01

from decimal import Decimal

import _socket
import django.contrib.sites.models
import django.core.validators
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import edc_registration.models.managers
import edc_sites.managers
import edc_utils.date
from django.conf import settings
from django.db import migrations, models

import edc_pharmacy.models.medication.medication
import edc_pharmacy.models.stock.managers
import edc_pharmacy.models.stock.order


class Migration(migrations.Migration):

    dependencies = [
        ("django_pylabels", "0004_alter_labelspecification_label_description_and_more"),
        ("edc_pharmacy", "0028_repackrequest_stockrequest_stockrequestitem_and_more"),
        ("edc_pylabels", "0006_delete_drawing"),
        ("edc_registration", "0031_alter_historicalregisteredsubject_site_and_more"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericcontainer",
            name="box",
        ),
        migrations.RemoveField(
            model_name="genericcontainer",
            name="container_type",
        ),
        migrations.RemoveField(
            model_name="historicallabels",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicallabels",
            name="stock_create_labels",
        ),
        migrations.RemoveField(
            model_name="historicalmedicationlot",
            name="formulation",
        ),
        migrations.RemoveField(
            model_name="historicalmedicationlot",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalstockcreatelabels",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalstockcreatelabels",
            name="product",
        ),
        migrations.RemoveField(
            model_name="historicalstockreceiving",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalstockreceiving",
            name="product",
        ),
        migrations.DeleteModel(
            name="HistoricalStockRequestProcessing",
        ),
        migrations.DeleteModel(
            name="HistoricalStockTransfer",
        ),
        migrations.RemoveField(
            model_name="labels",
            name="stock_create_labels",
        ),
        migrations.RemoveField(
            model_name="medicationlot",
            name="formulation",
        ),
        migrations.RemoveField(
            model_name="product",
            name="medication_lot",
        ),
        migrations.RemoveField(
            model_name="pillbottle",
            name="medication_lot",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="medication_lot",
        ),
        migrations.RemoveField(
            model_name="subjectpillbottle",
            name="medication_lot",
        ),
        migrations.RemoveField(
            model_name="pillbottle",
            name="box",
        ),
        migrations.RemoveField(
            model_name="pillbottle",
            name="container_type",
        ),
        migrations.RemoveField(
            model_name="pillbottle",
            name="formulation",
        ),
        migrations.RemoveField(
            model_name="pillbottle",
            name="source_container",
        ),
        migrations.RemoveField(
            model_name="subjectpillbottle",
            name="source_container",
        ),
        migrations.RemoveField(
            model_name="stockcreatelabels",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stockreceiving",
            name="product",
        ),
        migrations.RemoveField(
            model_name="subjectpillbottle",
            name="box",
        ),
        migrations.RemoveField(
            model_name="subjectpillbottle",
            name="container_type",
        ),
        migrations.RemoveField(
            model_name="subjectpillbottle",
            name="formulation",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.CreateModel(
            name="LabelSpecificationProxy",
            fields=[],
            options={
                "verbose_name": "Label Sheet Specification",
                "verbose_name_plural": "Label Sheet Specifications",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_pylabels.labelspecification",),
        ),
        migrations.CreateModel(
            name="RegisteredSubjectProxy",
            fields=[],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "proxy": True,
                "default_permissions": ("view", "export"),
                "indexes": [],
                "constraints": [],
            },
            bases=("edc_registration.registeredsubject",),
            managers=[
                (
                    "objects",
                    edc_registration.models.managers.RegisteredSubjectManager(),
                ),
                ("on_site", edc_sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name="SiteProxy",
            fields=[],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sites.site",),
            managers=[
                ("objects", django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
    ]
