# Generated by Django 5.1.2 on 2024-10-31 22:08

import edc_utils.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0028_remove_historicallocation_history_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorderitem",
            name="order_item_identifier",
            field=models.CharField(db_index=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="historicalreceive",
            name="item_count",
            field=models.IntegerField(null=True, verbose_name="Item count"),
        ),
        migrations.AddField(
            model_name="historicalreceiveitem",
            name="name",
            field=models.CharField(
                blank=True, help_text="Leave blank to use default", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalreceiveitem",
            name="receive_item_identifier",
            field=models.CharField(db_index=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="stock_datetime",
            field=models.DateTimeField(default=edc_utils.date.get_utcnow),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order_item_identifier",
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="receive",
            name="item_count",
            field=models.IntegerField(null=True, verbose_name="Item count"),
        ),
        migrations.AddField(
            model_name="receiveitem",
            name="name",
            field=models.CharField(
                blank=True, help_text="Leave blank to use default", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="receiveitem",
            name="receive_item_identifier",
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="stock_datetime",
            field=models.DateTimeField(default=edc_utils.date.get_utcnow),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="product_identifier",
            field=models.CharField(db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreceive",
            name="receive_identifier",
            field=models.CharField(db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="stock_identifier",
            field=models.CharField(db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_identifier",
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="receive",
            name="receive_identifier",
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_identifier",
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
