# Generated by Django 5.1.2 on 2024-11-02 01:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0029_historicalorderitem_order_item_identifier_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="container",
            old_name="container_qty",
            new_name="qty",
        ),
        migrations.RenameField(
            model_name="container",
            old_name="container_units",
            new_name="units",
        ),
        migrations.RemoveField(
            model_name="historicalorder",
            name="container_qty",
        ),
        migrations.RemoveField(
            model_name="historicalorder",
            name="unit_qty",
        ),
        migrations.RemoveField(
            model_name="historicalorderitem",
            name="container_qty",
        ),
        migrations.RemoveField(
            model_name="historicalorderitem",
            name="container_qty_received",
        ),
        migrations.RemoveField(
            model_name="historicalreceiveitem",
            name="container_qty",
        ),
        migrations.RemoveField(
            model_name="historicalstock",
            name="container_qty",
        ),
        migrations.RemoveField(
            model_name="historicalstock",
            name="container_qty_in",
        ),
        migrations.RemoveField(
            model_name="historicalstock",
            name="container_qty_out",
        ),
        migrations.RemoveField(
            model_name="order",
            name="container_qty",
        ),
        migrations.RemoveField(
            model_name="order",
            name="unit_qty",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="container_qty",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="container_qty_received",
        ),
        migrations.RemoveField(
            model_name="receiveitem",
            name="container_qty",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="container_qty",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="container_qty_in",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="container_qty_out",
        ),
        migrations.AddField(
            model_name="container",
            name="may_receive_as",
            field=models.BooleanField(
                default=True, verbose_name="Container may be used for receiving"
            ),
        ),
        migrations.AddField(
            model_name="historicalorderitem",
            name="qty",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalorderitem",
            name="unit_qty_received",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
        migrations.AddField(
            model_name="historicalreceiveitem",
            name="qty",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="qty_in",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="qty_out",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="qty",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_qty_received",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
        migrations.AddField(
            model_name="receiveitem",
            name="qty",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="qty_in",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="qty_out",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="order_identifier",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="order_item_identifier",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="unit_qty",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="product_identifier",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreceive",
            name="receive_identifier",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreceiveitem",
            name="receive_item_identifier",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreceiveitem",
            name="unit_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantity x Container.Quantity, e.g. 10 x Bottle of 128 = 1280",
                max_digits=20,
                null=True,
                verbose_name="Unit quantity",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="stock_identifier",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="unit_qty_in",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="unit_qty_out",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_identifier",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order_item_identifier",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_qty",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_identifier",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="receive",
            name="receive_identifier",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="receiveitem",
            name="receive_item_identifier",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="receiveitem",
            name="unit_qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Quantity x Container.Quantity, e.g. 10 x Bottle of 128 = 1280",
                max_digits=20,
                null=True,
                verbose_name="Unit quantity",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_identifier",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="unit_qty_in",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
        migrations.AlterField(
            model_name="stock",
            name="unit_qty_out",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
    ]
