# Generated by Django 5.1.2 on 2024-11-07 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0029_historicalrepackrequest_processed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repackrequest",
            name="stock_items",
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="repack_request",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.repackrequest",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="repack_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.repackrequest",
            ),
        ),
    ]
