# Generated by Django 5.1.2 on 2024-11-09 21:03

from decimal import Decimal

import _socket
import django.core.validators
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import edc_utils.date
from django.conf import settings
from django.db import migrations, models

import edc_pharmacy.models.medication.medication
import edc_pharmacy.models.stock.managers
import edc_pharmacy.models.stock.order


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0029_remove_genericcontainer_box_and_more"),
        ("edc_pylabels", "0006_delete_drawing"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="GenericContainer",
        ),
        migrations.DeleteModel(
            name="HistoricalLabels",
        ),
        migrations.DeleteModel(
            name="HistoricalMedicationLot",
        ),
        migrations.DeleteModel(
            name="HistoricalStockCreateLabels",
        ),
        migrations.DeleteModel(
            name="HistoricalStockReceiving",
        ),
        migrations.DeleteModel(
            name="Labels",
        ),
        migrations.DeleteModel(
            name="MedicationLot",
        ),
        migrations.DeleteModel(
            name="PillBottle",
        ),
        migrations.DeleteModel(
            name="StockCreateLabels",
        ),
        migrations.DeleteModel(
            name="StockReceiving",
        ),
        migrations.DeleteModel(
            name="SubjectPillBottle",
        ),
    ]
