# Generated by Django 5.1.2 on 2024-11-09 21:04

from decimal import Decimal

import _socket
import django.core.validators
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import edc_utils.date
from django.conf import settings
from django.db import migrations, models

import edc_pharmacy.models.medication.medication
import edc_pharmacy.models.stock.managers
import edc_pharmacy.models.stock.order


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_pharmacy",
            "0030_delete_genericcontainer_delete_historicallabels_and_more",
        ),
        ("edc_pylabels", "0006_delete_drawing"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="container",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Container",
                "verbose_name_plural": "Containers",
            },
        ),
        migrations.AlterModelOptions(
            name="containertype",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Container type",
                "verbose_name_plural": "Container types",
            },
        ),
        migrations.AlterModelOptions(
            name="formulationtype",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Formulation type",
                "verbose_name_plural": "Formulation types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalassignment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Assignment",
                "verbose_name_plural": "historical Assignments",
            },
        ),
        migrations.AlterModelOptions(
            name="historicallot",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Lot",
                "verbose_name_plural": "historical Lots",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalorder",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Order",
                "verbose_name_plural": "historical Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproduct",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Product",
                "verbose_name_plural": "historical Product",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalrxrefill",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Prescription: Refill",
                "verbose_name_plural": "historical Prescription: Refills",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstock",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Stock",
                "verbose_name_plural": "historical Stock",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.AlterModelOptions(
            name="lot",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Lot",
                "verbose_name_plural": "Lots",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Product",
                "verbose_name_plural": "Product",
            },
        ),
        migrations.AlterModelOptions(
            name="rxrefill",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Prescription: Refill",
                "verbose_name_plural": "Prescription: Refills",
            },
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "Stock",
                "verbose_name_plural": "Stock",
            },
        ),
        migrations.AlterModelManagers(
            name="medication",
            managers=[
                ("objects", edc_pharmacy.models.medication.medication.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="order",
            managers=[
                ("objects", edc_pharmacy.models.stock.order.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="product",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="stock",
            managers=[
                ("objects", edc_pharmacy.models.stock.managers.StockManager()),
            ],
        ),
    ]
