# Generated by Django 5.1.2 on 2024-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0030_remove_repackrequest_stock_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulation",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="historicalformulation",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
