# Generated by Django 5.1.2 on 2024-11-09 21:05

from decimal import Decimal

import _socket
import django.core.validators
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import edc_utils.date
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_pharmacy",
            "0031_alter_container_options_alter_containertype_options_and_more",
        ),
        ("edc_pylabels", "0006_delete_drawing"),
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="container",
            name="edc_pharmac_display_0172ab_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="edc_pharmac_modifie_c4a1aa_idx",
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="edc_pharmac_user_mo_1838af_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="edc_pharmac_subject_36f4ea_idx",
        ),
        migrations.RemoveField(
            model_name="container",
            name="display_index",
        ),
        migrations.RemoveField(
            model_name="container",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="container",
            name="extra_value",
        ),
        migrations.RemoveField(
            model_name="container",
            name="field_name",
        ),
        migrations.RemoveField(
            model_name="container",
            name="plural_name",
        ),
        migrations.RemoveField(
            model_name="container",
            name="version",
        ),
        migrations.RemoveField(
            model_name="historicalorder",
            name="product",
        ),
        migrations.RemoveField(
            model_name="historicalorder",
            name="qty_ordered",
        ),
        migrations.RemoveField(
            model_name="historicalorder",
            name="qty_supplied",
        ),
        migrations.RemoveField(
            model_name="historicalorder",
            name="subject_identifier",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="container",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="count_per_container",
        ),
        migrations.RemoveField(
            model_name="historicalproduct",
            name="site",
        ),
        migrations.RemoveField(
            model_name="historicalreceiveitem",
            name="added_to_stock",
        ),
        migrations.RemoveField(
            model_name="historicalrepackrequest",
            name="stock_identifier",
        ),
        migrations.RemoveField(
            model_name="historicalstock",
            name="site",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="code",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="crf",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="crf_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="dispensed",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="dispensed_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="printed",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="printed_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="scanned",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="scanned_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="sid",
        ),
        migrations.RemoveField(
            model_name="historicalstockrequestitem",
            name="subject_identifier",
        ),
        migrations.RemoveField(
            model_name="location",
            name="created",
        ),
        migrations.RemoveField(
            model_name="location",
            name="description",
        ),
        migrations.RemoveField(
            model_name="location",
            name="device_created",
        ),
        migrations.RemoveField(
            model_name="location",
            name="device_modified",
        ),
        migrations.RemoveField(
            model_name="location",
            name="hostname_created",
        ),
        migrations.RemoveField(
            model_name="location",
            name="hostname_modified",
        ),
        migrations.RemoveField(
            model_name="location",
            name="locale_created",
        ),
        migrations.RemoveField(
            model_name="location",
            name="locale_modified",
        ),
        migrations.RemoveField(
            model_name="location",
            name="location_datetime",
        ),
        migrations.RemoveField(
            model_name="location",
            name="location_identifier",
        ),
        migrations.RemoveField(
            model_name="location",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="location",
            name="revision",
        ),
        migrations.RemoveField(
            model_name="location",
            name="user_created",
        ),
        migrations.RemoveField(
            model_name="location",
            name="user_modified",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="qty_ordered",
        ),
        migrations.RemoveField(
            model_name="order",
            name="qty_supplied",
        ),
        migrations.RemoveField(
            model_name="order",
            name="subject_identifier",
        ),
        migrations.RemoveField(
            model_name="product",
            name="container",
        ),
        migrations.RemoveField(
            model_name="product",
            name="count_per_container",
        ),
        migrations.RemoveField(
            model_name="product",
            name="site",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="site",
        ),
    ]
