# Generated by Django 5.1.2 on 2024-11-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0031_rename_assignment_assignment_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorderitem",
            name="unit_qty",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="unit_qty_received",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_qty",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_qty_received",
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
