# Generated by Django 5.1.2 on 2024-11-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0031_formulation_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="qty_decimal_places",
            field=models.IntegerField(default=0),
        ),
    ]
