# Generated by Django 5.1.2 on 2024-11-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0032_alter_historicalorderitem_unit_qty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstock",
            name="human_readable_code",
            field=models.CharField(db_index=True, default="-", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="human_readable_code",
            field=models.CharField(default="-", max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
