# Generated by Django 5.1.2 on 2024-11-09 21:52

import django.db.models.deletion
import django_audit_fields.fields.uuid_auto_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0033_allocation_label_configuration_and_more"),
        ("edc_pylabels", "0006_delete_drawing"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="id",
            field=django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                blank=True,
                editable=False,
                help_text="System auto field. UUID primary key.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="name",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Leave blank to use default",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="product_identifier",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="historicalrx",
            name="registered_subject",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.registeredsubjectproxy",
                verbose_name="Subject Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="stock_identifier",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name="historicalstockrequestitem",
            name="received_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                help_text="This is the stored value, required",
                max_length=250,
                unique=True,
                verbose_name="Stored value",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use default",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_identifier",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="rx",
            name="registered_subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.registeredsubjectproxy",
                verbose_name="Subject Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_identifier",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
