# Generated by Django 5.1.2 on 2024-11-08 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0033_remove_historicalreceiveitem_added_to_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreceiveitem",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.lot",
            ),
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.lot",
            ),
        ),
        migrations.AddField(
            model_name="receiveitem",
            name="lot",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="edc_pharmacy.lot"
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="lot",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="edc_pharmacy.lot"
            ),
        ),
    ]
