# Generated by Django 5.1.2 on 2024-11-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0033_historicalstock_human_readable_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalstock",
            old_name="human_readable_code",
            new_name="stock_code",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="human_readable_code",
            new_name="stock_code",
        ),
    ]
