# Generated by Django 5.1.2 on 2024-11-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0034_historicalreceiveitem_lot_historicalstock_lot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstock",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="code",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
