# Generated by Django 5.1.2 on 2024-11-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0034_alter_container_id_alter_container_name_and_more"),
        ("edc_pylabels", "0006_delete_drawing"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_93b5ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allocation",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_009406_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_46b9fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_0d441d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_3a103a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_cb1dc7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="containerunits",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="edc_pharmac_display_ff6b48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["display_index", "display_name"],
                name="edc_pharmac_display_c5b56a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_50c644_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_227b04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_76214d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_cc450e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receive",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_ca1746_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receive",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_661efc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receiveitem",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_a8e559_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receiveitem",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_cdf3df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repackrequest",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_e9be1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repackrequest",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_e152ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockrequest",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_296292_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockrequest",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_02bc39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockrequestitem",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_338d5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockrequestitem",
            index=models.Index(
                fields=["user_modified", "user_created"],
                name="edc_pharmac_user_mo_c76cb8_idx",
            ),
        ),
    ]
