# Generated by Django 5.1.2 on 2024-11-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_pharmacy",
            "0034_rename_human_readable_code_historicalstock_stock_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstock",
            name="stock_code",
            field=models.CharField(
                db_index=True, help_text="Human readable code", max_length=15
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_code",
            field=models.CharField(
                help_text="Human readable code", max_length=15, unique=True
            ),
        ),
    ]
