# Generated by Django 5.1.2 on 2024-11-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0035_historicalstock_code_stock_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="may_dispense_as",
            field=models.BooleanField(
                default=False, verbose_name="Container may be used for dispensing to subject"
            ),
        ),
    ]
