# Generated by Django 5.1.2 on 2024-11-09 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0037_alter_location_options_location_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstock",
            name="repack_request",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.repackrequest",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="repack_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.repackrequest",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreceive",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={"site__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.location",
            ),
        ),
        migrations.AlterField(
            model_name="receive",
            name="location",
            field=models.ForeignKey(
                limit_choices_to={"site__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.location",
            ),
        ),
    ]
