# Generated by Django 5.1.2 on 2024-11-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0038_historicalstock_repack_request_stock_repack_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstock",
            name="random_identifier",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="random_identifier",
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
