# Generated by Django 5.1.2 on 2024-11-10 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0039_historicalstock_random_identifier_and_more"),
        ("edc_pylabels", "0007_alter_labelconfiguration_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstock",
            name="random_identifier",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="random_identifier",
        ),
        migrations.AddField(
            model_name="historicalrepackrequest",
            name="label_configuration",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pylabels.labelconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="repackrequest",
            name="label_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pylabels.labelconfiguration",
            ),
        ),
    ]
