# Generated by Django 5.1.2 on 2024-11-10 18:21

import django.db.models.deletion
import edc_utils.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0040_remove_historicalstock_random_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstock",
            name="confirmed_by_identifier",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="confirmed_by_identifier",
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="allocation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Subject allocation",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.allocation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A unique alphanumeric code",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="confirmed",
            field=models.BooleanField(
                default=False,
                help_text="True if stock was labelled and confirmed; False if stock was received/repacked but never confirmed.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="stock_datetime",
            field=models.DateTimeField(
                default=edc_utils.date.get_utcnow, help_text="date stock record created"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="stock_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A sequential unique identifier for the stock",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="allocation",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject allocation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.allocation",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="A unique alphanumeric code",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="confirmed",
            field=models.BooleanField(
                default=False,
                help_text="True if stock was labelled and confirmed; False if stock was received/repacked but never confirmed.",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_datetime",
            field=models.DateTimeField(
                default=edc_utils.date.get_utcnow, help_text="date stock record created"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier for the stock",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
    ]
