# Generated by Django 5.1.2 on 2024-11-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0042_supplier_historicalsupplier_historicalorder_supplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalreceive",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receive",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
