# Generated by Django 5.1.2 on 2024-11-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0043_historicalorder_comment_historicalreceive_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="title",
            field=models.CharField(
                help_text="A short description of this order", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="title",
            field=models.CharField(
                help_text="A short description of this order", max_length=50, null=True
            ),
        ),
    ]
