# Generated by Django 5.1.2 on 2024-11-10 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0044_historicalorder_title_order_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="receive_item",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.receiveitem",
            ),
        ),
    ]
