# Generated by Django 5.1.2 on 2024-11-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0045_alter_stock_receive_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstockrequest",
            name="subject_identifiers",
            field=models.TextField(
                blank=True,
                help_text="By adding subject identifiers in this box, only these subjects will be included in the request. All others will be ignored.",
                null=True,
                verbose_name="Include ONLY these subjects in this request",
            ),
        ),
        migrations.AddField(
            model_name="stockrequest",
            name="subject_identifiers",
            field=models.TextField(
                blank=True,
                help_text="By adding subject identifiers in this box, only these subjects will be included in the request. All others will be ignored.",
                null=True,
                verbose_name="Include ONLY these subjects in this request",
            ),
        ),
    ]
