# Generated by Django 5.1.2 on 2024-11-11 01:59

import _socket
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import edc_utils.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0047_historicalstockrequest_excluded_subject_identifiers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispense",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dispense_identifier",
                    models.CharField(blank=True, max_length=36, null=True, unique=True),
                ),
                ("dispense_datetime", models.DateTimeField(default=edc_utils.date.get_utcnow)),
                ("to_clinician", models.BooleanField(default=False)),
                ("to_clinician_datetime", models.DateTimeField(blank=True, null=True)),
                ("to_subject", models.BooleanField(default=False)),
                ("to_subject_datetime", models.DateTimeField(blank=True, null=True)),
                ("crf_label_lower", models.CharField(blank=True, max_length=100, null=True)),
                ("crf_field_name", models.CharField(blank=True, max_length=100, null=True)),
                ("crf_id", models.UUIDField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="edc_pharmacy.location",
                    ),
                ),
                (
                    "registered_subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="edc_pharmacy.registeredsubjectproxy",
                        verbose_name="Subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispense",
                "verbose_name_plural": "Dispense",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "default_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="historicalstock",
            name="dispense",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Stock was dispensed",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.dispense",
                verbose_name="Dispense",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="dispense",
            field=models.OneToOneField(
                blank=True,
                help_text="Stock was dispensed",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.dispense",
                verbose_name="Dispense",
            ),
        ),
        migrations.AddIndex(
            model_name="dispense",
            index=models.Index(
                fields=["modified", "created"], name="edc_pharmac_modifie_57ed59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispense",
            index=models.Index(
                fields=["user_modified", "user_created"], name="edc_pharmac_user_mo_31c262_idx"
            ),
        ),
    ]
