# Generated by Django 5.1.2 on 2024-11-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0048_dispense_historicalstock_dispense_stock_dispense_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allocation",
            name="label_configuration",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="rando_sid",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="rx",
        ),
        migrations.AddField(
            model_name="allocation",
            name="allocated_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
