# Generated by Django 5.1.2 on 2024-11-11 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0049_remove_allocation_label_configuration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="allocation",
            field=models.OneToOneField(
                blank=True,
                help_text="Subject allocation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.allocation",
            ),
        ),
    ]
