# Generated by Django 5.1.2 on 2024-11-12 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0050_alter_stock_allocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalreceive",
            name="confirmed_stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="historicalreceive",
            name="label_configuration",
        ),
        migrations.RemoveField(
            model_name="historicalreceive",
            name="stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="historicalreceive",
            name="unconfirmed_stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="historicalrepackrequest",
            name="confirmed_stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="historicalrepackrequest",
            name="label_configuration",
        ),
        migrations.RemoveField(
            model_name="historicalrepackrequest",
            name="stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="historicalrepackrequest",
            name="unconfirmed_stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="historicalstock",
            name="label_configuration",
        ),
        migrations.RemoveField(
            model_name="receive",
            name="confirmed_stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="receive",
            name="label_configuration",
        ),
        migrations.RemoveField(
            model_name="receive",
            name="stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="receive",
            name="unconfirmed_stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="repackrequest",
            name="confirmed_stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="repackrequest",
            name="label_configuration",
        ),
        migrations.RemoveField(
            model_name="repackrequest",
            name="stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="repackrequest",
            name="unconfirmed_stock_identifiers",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="label_configuration",
        ),
    ]
