# Generated by Django 5.1.2 on 2024-11-12 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0051_remove_historicalreceive_confirmed_stock_identifiers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="assignment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.assignment",
            ),
        ),
    ]
