# Generated by Django 5.1.2 on 2024-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0053_historicalstockrequestitem_assignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallot",
            name="lot_identifier",
            field=models.CharField(db_index=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="lot_identifier",
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A unique alphanumeric code",
                max_length=15,
                null=True,
                verbose_name="Stock code",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="stock_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A sequential unique identifier for the stock",
                max_length=36,
                null=True,
                verbose_name="Internal stock identifier",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="A unique alphanumeric code",
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Stock code",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier for the stock",
                max_length=36,
                null=True,
                unique=True,
                verbose_name="Internal stock identifier",
            ),
        ),
    ]
