# Generated by Django 5.1.2 on 2024-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0054_historicallot_lot_identifier_lot_lot_identifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproduct",
            name="name",
            field=models.CharField(
                blank=True, help_text="Leave blank to use default", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                blank=True, help_text="Leave blank to use default", max_length=50
            ),
        ),
    ]
