# Generated by Django 5.1.2 on 2024-11-12 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0055_alter_historicalproduct_name_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorderitem",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.assignment",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="assignment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="edc_pharmacy.assignment",
            ),
        ),
    ]
