# Generated by Django 5.1.2 on 2024-11-13 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0057_remove_historicalorderitem_assignment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransfer",
            name="from_location",
            field=models.ForeignKey(
                limit_choices_to={"site__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="from_location",
                to="edc_pharmacy.location",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="to_location",
            field=models.ForeignKey(
                limit_choices_to={"site__isnull": False},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="to_location",
                to="edc_pharmacy.location",
            ),
        ),
    ]
