# Generated by Django 5.1.2 on 2024-11-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0059_alter_stocktransfer_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransferitem",
            name="from_location",
        ),
        migrations.RemoveField(
            model_name="stocktransferitem",
            name="to_location",
        ),
        migrations.AlterField(
            model_name="allocation",
            name="allocation_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="dispense",
            name="dispense_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicallot",
            name="lot_identifier",
            field=models.CharField(
                db_index=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorder",
            name="order_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalorderitem",
            name="order_item_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalproduct",
            name="product_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalreceive",
            name="receive_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalreceiveitem",
            name="receive_item_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalrepackrequest",
            name="repack_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalstock",
            name="stock_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                verbose_name="Internal stock identifier",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstockrequest",
            name="request_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalstockrequestitem",
            name="request_item_identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="lot_identifier",
            field=models.CharField(
                help_text="A sequential unique identifier set by the EDC",
                max_length=25,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order_item_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="receive",
            name="receive_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="receiveitem",
            name="receive_item_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="repackrequest",
            name="repack_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
                verbose_name="Internal stock identifier",
            ),
        ),
        migrations.AlterField(
            model_name="stockrequest",
            name="request_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockrequestitem",
            name="request_item_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="transfer_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="stocktransferitem",
            name="transfer_item_identifier",
            field=models.CharField(
                blank=True,
                help_text="A sequential unique identifier set by the EDC",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
    ]
