from .autocomplete_admin import SubjectAdmin
from .dispensing_history_admin import DispensingHistoryAdmin
from .dosage_guideline_admin import DosageGuidelineAdmin
from .medication_admin import MedicationAdmin
from .prescription_admin import PrescriptionAdmin
from .prescription_item_admin import PrescriptionItemAdmin
from .return_history_admin import ReturnHistoryAdmin
